#!/usr/bin/env python3
"""generate-policy.py: write a personalized fivedrisk policy.yaml.

Inputs:
    --preset PATH    Path to the bundled openclaw_agent.yaml preset
                     (see references/openclaw_agent.yaml in this skill)
    --scan PATH      Path to the JSON output of scan-setup.py
                     (use "-" to read from stdin)
    --out PATH       Where to write the personalized policy.yaml
                     (default: ~/.fivedrisk/policy.yaml; respects
                     FIVEDRISK_POLICY_PATH env var)
    --force          Overwrite an existing output file (off by default)
    --dry-run        Print the would-be output to stdout, don't write

Behavior:
    1. Read the preset verbatim (it is text-stable YAML).
    2. Read the scan JSON.
    3. Build a small set of overrides based on the scan:
       - Assert Bash overrides for rm -rf and curl|sh are present in
         the preset; refuse to proceed if not (defense in depth, in case
         the bundled preset was tampered with).
       - For each MCP server in the scan, emit a stub tool_defaults
         entry under its declared tool names with conservative scores
         (tool_privilege=2, reversibility=2, external_impact=1; bumped
         to tool_privilege=3 if the tool name looks privileged).
    4. Write a generated-header comment block, the preset body, then the
       generated overrides as an appended YAML block.

Stdlib only. No PyYAML dependency, so the merge is done by text
concatenation with deterministic key ordering. The fivedrisk library
parses the resulting file with its own YAML loader at policy-load time.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
from pathlib import Path
from typing import Any

# Match the literal YAML-quoted forms as they appear in the preset file
# on disk. Backslashes inside a YAML double-quoted string are escaped, so
# the pipe in "curl.*\|.*sh" is stored as `\\|` in the bytes on disk.
REQUIRED_BASH_KEYS = ("rm -rf", "curl.*\\\\|.*sh")

PRIVILEGED_TOOL_MARKERS = ("shell", "exec", "spawn", "write", "delete", "kill")


def _utc_now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _default_policy_path() -> Path:
    env = os.environ.get("FIVEDRISK_POLICY_PATH")
    if env:
        return Path(env).expanduser()
    return Path.home() / ".fivedrisk" / "policy.yaml"


def _read_text(path: Path) -> str:
    with path.open("r", encoding="utf-8") as fh:
        return fh.read()


def _read_scan(path: str) -> dict[str, Any]:
    if path == "-":
        return json.load(sys.stdin)
    with Path(path).expanduser().open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _assert_preset_integrity(preset_text: str) -> list[str]:
    """Return a list of missing required keys. Empty means OK."""
    missing: list[str] = []
    for key in REQUIRED_BASH_KEYS:
        # The preset YAML quotes these keys. We check for the quoted form.
        if f'"{key}"' not in preset_text:
            missing.append(key)
    return missing


def _looks_privileged(tool_name: str) -> bool:
    name = tool_name.lower()
    return any(marker in name for marker in PRIVILEGED_TOOL_MARKERS)


def _scan_summary_block(scan: dict[str, Any]) -> str:
    skills = scan.get("skills") or []
    mcp_servers = scan.get("mcp_servers") or []
    tool_surface = scan.get("tool_surface") or []
    warnings = scan.get("warnings") or []
    lines: list[str] = []
    lines.append(f"# Generated by 5D Claw Security skill v0.1.0 at {_utc_now_iso()}")
    lines.append(f"# Scan: openclaw_home={scan.get('openclaw_home', '?')}")
    lines.append(
        "# Scan summary: "
        f"{len(skills)} skill(s), {len(mcp_servers)} MCP server(s), "
        f"tool_surface={tool_surface}"
    )
    if warnings:
        lines.append("# Scan warnings:")
        for w in warnings:
            lines.append(f"#   - {w}")
    lines.append("# This file may be hand-edited. Restart OpenClaw for changes to apply.")
    lines.append("# Field documentation: references/policy-yaml-primer.md in this skill.")
    lines.append("")
    return "\n".join(lines)


def _generated_overrides_block(scan: dict[str, Any]) -> str:
    """Build the appended overrides YAML based on the scan.

    The fivedrisk policy loader merges later definitions over earlier
    ones within the same file, so appending a `tool_defaults` block at
    the end is the supported override mechanism.
    """
    mcp_servers = scan.get("mcp_servers") or []
    if not mcp_servers:
        return ""
    lines: list[str] = []
    lines.append("")
    lines.append("# --- Generated overrides for detected MCP tools ---")
    lines.append("# Each MCP-declared tool gets a conservative starting score.")
    lines.append("# Tune these after a week of observed decisions.")
    lines.append("tool_defaults:")
    seen: set[str] = set()
    for server in mcp_servers:
        if not isinstance(server, dict):
            continue
        tools = server.get("tools_declared") or []
        if not isinstance(tools, list):
            continue
        server_name = server.get("name", "?")
        for tool in tools:
            tool_str = str(tool).strip()
            if not tool_str or tool_str in seen:
                continue
            seen.add(tool_str)
            priv = 3 if _looks_privileged(tool_str) else 2
            lines.append(f"  # from MCP server: {server_name}")
            lines.append(f"  {tool_str}:")
            lines.append(f"    tool_privilege: {priv}")
            lines.append("    reversibility: 2")
            lines.append("    external_impact: 1")
    if not seen:
        return ""
    return "\n".join(lines) + "\n"


def _build_output(preset_text: str, scan: dict[str, Any]) -> str:
    header = _scan_summary_block(scan)
    overrides = _generated_overrides_block(scan)
    body = preset_text
    if not body.endswith("\n"):
        body += "\n"
    return header + body + overrides


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a personalized fivedrisk policy.yaml."
    )
    parser.add_argument(
        "--preset",
        type=Path,
        required=True,
        help="Path to the bundled openclaw_agent.yaml preset",
    )
    parser.add_argument(
        "--scan",
        default="-",
        help='Path to scan JSON, or "-" for stdin (default: stdin)',
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: ~/.fivedrisk/policy.yaml or $FIVEDRISK_POLICY_PATH)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing output file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the would-be output to stdout, don't write",
    )
    args = parser.parse_args(argv)

    preset_path = args.preset.expanduser()
    if not preset_path.exists():
        print(f"error: preset not found: {preset_path}", file=sys.stderr)
        return 2

    preset_text = _read_text(preset_path)
    missing = _assert_preset_integrity(preset_text)
    if missing:
        print(
            "error: bundled preset failed integrity check; missing required "
            f"keys: {missing}. Refusing to generate a policy from a tampered "
            "preset. Re-install the skill.",
            file=sys.stderr,
        )
        return 3

    scan = _read_scan(args.scan)
    if not isinstance(scan, dict) or scan.get("schema_version") != 1:
        print(
            "error: scan input does not match expected schema_version=1; "
            "did you run scripts/scan-setup.py?",
            file=sys.stderr,
        )
        return 4

    out_text = _build_output(preset_text, scan)

    if args.dry_run:
        sys.stdout.write(out_text)
        return 0

    out_path = (args.out or _default_policy_path()).expanduser()
    if out_path.exists() and not args.force:
        print(
            f"error: refusing to overwrite existing {out_path}. "
            "Re-run with --force, or back up the existing file.",
            file=sys.stderr,
        )
        return 5

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as fh:
        fh.write(out_text)
    print(f"wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
